// Generate src/generated/** from ./assets. Pure and deterministic: same assets in,
// byte-identical output out. Run with `pnpm codegen` (also runs as prebuild/pretest).

import { readFile, rm, mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Catalog, CatalogEntry, TagsIndex } from "./lib/catalog.ts";
import { assertNoCollisions, componentName, pngConstName, svgConstName } from "./lib/naming.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS = join(ROOT, "assets");
const VECTORS = join(ASSETS, "vectors");
const OUT = join(ROOT, "src", "generated");

const HEADER = "// AUTO-GENERATED by scripts/codegen.ts — do not edit.\n";
const VIEWBOX_RE = /viewBox\s*=\s*["']([^"']+)["']/i;

function svgBody(svg: string): string {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  return svg.slice(open + 1, close).trim();
}

async function writeOut(relPath: string, content: string): Promise<void> {
  const full = join(OUT, relPath);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, content);
}

async function main(): Promise<void> {
  const catalog = JSON.parse(await readFile(join(ASSETS, "catalog.json"), "utf8")) as Catalog;
  const tags = JSON.parse(await readFile(join(ASSETS, "tags.json"), "utf8")) as TagsIndex;
  const entries = catalog.entries;

  assertNoCollisions(entries.map((e) => e.slug));

  // Fresh output every run keeps determinism (no stale modules from removed assets).
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  for (const entry of entries) {
    await writeMeta(entry);
    await writePng(entry);
    if (entry.delivery === "svg") await writeSvg(entry);
    await writeComponent(entry);
  }

  await writeComponentBarrel(entries);
  await writeSvgBarrel(entries);
  await writePngBarrel(entries);
  await writeManifest(entries);
  await writeLoaders(entries);
  await writeTags(tags);

  const svgCount = entries.filter((e) => e.delivery === "svg").length;
  console.log(
    `codegen: ${entries.length} assets (${svgCount} svg, ${entries.length - svgCount} png) → src/generated`,
  );
}

async function writeMeta(entry: CatalogEntry): Promise<void> {
  const meta = {
    slug: entry.slug,
    name: entry.name,
    version: entry.version,
    imageType: entry.imageType,
    usageType: entry.usageType,
    team: entry.team,
    caption: entry.caption,
    tags: entry.tags,
    pathTags: entry.pathTags,
    colors: entry.colors,
    hedgehogs: entry.hedgehogs,
    verified: entry.verified,
    delivery: entry.delivery,
    aspectRatio: entry.aspectRatio,
    files: entry.files,
  };
  await writeOut(
    `meta/${entry.slug}.ts`,
    `${HEADER}import type { HedgehogMeta } from "../../types.ts";\n\n` +
      `export const meta: HedgehogMeta = ${JSON.stringify(meta, null, 2)};\n\n` +
      `export default meta;\n`,
  );
}

async function writePng(entry: CatalogEntry): Promise<void> {
  await writeOut(
    `png/${entry.slug}.ts`,
    `${HEADER}` +
      `export const src: string = new URL(${JSON.stringify(`../../png/${entry.slug}.png`)}, import.meta.url).href;\n` +
      `export const aspectRatio: number = ${entry.aspectRatio};\n\n` +
      `export default src;\n`,
  );
}

async function writeSvg(entry: CatalogEntry): Promise<void> {
  const raw = await readFile(join(VECTORS, `${entry.slug}.svg`), "utf8");
  const viewBox = raw.match(VIEWBOX_RE)?.[1]?.trim() ?? "0 0 0 0";
  const body = svgBody(raw);
  await writeOut(
    `svg/${entry.slug}.ts`,
    `${HEADER}` +
      `export const viewBox: string = ${JSON.stringify(viewBox)};\n` +
      `export const body: string = ${JSON.stringify(body)};\n` +
      `export const svg: string = ${JSON.stringify(raw.trim())};\n\n` +
      `export default svg;\n`,
  );
}

async function writeComponent(entry: CatalogEntry): Promise<void> {
  const name = componentName(entry.slug);
  // Files are named by slug (unique + case-stable) so that component names which
  // differ only in case (e.g. bug-catcher vs bugcatcher) don't collide on
  // case-insensitive filesystems.
  if (entry.delivery === "svg") {
    await writeOut(
      `components/${entry.slug}.tsx`,
      `${HEADER}import { createHedgehog, type HedgehogComponent } from "../../runtime/create-hedgehog.tsx";\n` +
        `import { body, viewBox } from "../svg/${entry.slug}.ts";\n` +
        `import { meta } from "../meta/${entry.slug}.ts";\n\n` +
        `export const ${name}: HedgehogComponent = createHedgehog({ viewBox, body, meta });\n\n` +
        `export default ${name};\n`,
    );
  } else {
    await writeOut(
      `components/${entry.slug}.tsx`,
      `${HEADER}import { createPngHedgehog, type PngHedgehogComponent } from "../../runtime/create-png-hedgehog.tsx";\n` +
        `import { src } from "../png/${entry.slug}.ts";\n` +
        `import { meta } from "../meta/${entry.slug}.ts";\n\n` +
        `export const ${name}: PngHedgehogComponent = createPngHedgehog({ src, meta });\n\n` +
        `export default ${name};\n`,
    );
  }
}

async function writeComponentBarrel(entries: CatalogEntry[]): Promise<void> {
  const lines = entries.map((e) => `export { ${componentName(e.slug)} } from "./${e.slug}.tsx";`);
  await writeOut("components/index.ts", `${HEADER}${lines.join("\n")}\n`);
}

async function writeSvgBarrel(entries: CatalogEntry[]): Promise<void> {
  const lines = entries
    .filter((e) => e.delivery === "svg")
    .map((e) => `export { svg as ${svgConstName(e.slug)} } from "./${e.slug}.ts";`);
  await writeOut("svg/index.ts", `${HEADER}${lines.join("\n")}\n`);
}

async function writePngBarrel(entries: CatalogEntry[]): Promise<void> {
  const lines = entries.map(
    (e) => `export { src as ${pngConstName(e.slug)} } from "./${e.slug}.ts";`,
  );
  await writeOut("png/index.ts", `${HEADER}${lines.join("\n")}\n`);
}

async function writeManifest(entries: CatalogEntry[]): Promise<void> {
  const imports = entries
    .map((e, i) => `import { meta as m${i} } from "./meta/${e.slug}.ts";`)
    .join("\n");
  const array = entries.map((_, i) => `  m${i},`).join("\n");
  await writeOut(
    "manifest.ts",
    `${HEADER}import type { HedgehogMeta } from "../types.ts";\n${imports}\n\n` +
      `export const hedgehogs: HedgehogMeta[] = [\n${array}\n];\n`,
  );
}

async function writeLoaders(entries: CatalogEntry[]): Promise<void> {
  const svgLines = entries
    .filter((e) => e.delivery === "svg")
    .map((e) => `  ${JSON.stringify(e.slug)}: () => import("./svg/${e.slug}.ts"),`)
    .join("\n");
  await writeOut(
    "svg-loaders.ts",
    `${HEADER}export const svgLoaders: Record<string, () => Promise<{ svg: string }>> = {\n${svgLines}\n};\n`,
  );

  const pngLines = entries
    .map((e) => `  ${JSON.stringify(e.slug)}: () => import("./png/${e.slug}.ts"),`)
    .join("\n");
  await writeOut(
    "png-loaders.ts",
    `${HEADER}export const pngLoaders: Record<string, () => Promise<{ src: string }>> = {\n${pngLines}\n};\n`,
  );
}

async function writeTags(tags: TagsIndex): Promise<void> {
  const vocab = {
    freeform: tags.freeform,
    poses: tags.poses,
    expressions: tags.expressions,
    outfits: tags.outfits,
    accessories: tags.accessories,
    teams: tags.teams,
    pathTags: tags.pathTags,
  };
  await writeOut(
    "tags.ts",
    `${HEADER}import type { TagVocabulary } from "../types.ts";\n\n` +
      `export const tagVocabulary: TagVocabulary = ${JSON.stringify(vocab, null, 2)};\n`,
  );
}

await main();
